---    
- name: Install specific packages
  package:
    name:
      - nfs-kernel-server
    state: latest

- name: share directory exists
  ansible.builtin.file:
    path: "{{ mountShare }}"
    state: directory
    mode: "{{ mountSharePermission }}"
    owner: root
    group: root

- name: Mount up device by UUID
  ansible.posix.mount:
    path: "{{ mountShare }}"
    src: "{{ mountShareSource }}"
    fstype: "{{ mountShareType }}"
    opts: defaults,rw,noatime,auto
    boot: true
    state: mounted

- name: share in /etc/exports file
  ansible.builtin.lineinfile:
    path: /etc/exports
    state: present
    line: '{{ mountShare }} {{ mountShareOptions }}'
  notify: restart NFS server

- name: export share
  ansible.builtin.command: "exportfs -rav"